sudo: required

branches:
  only:
    - master

language: C

env:
 - ROUTER_NAME=hsl
 - ROUTER_NAME=waltti
 - ROUTER_NAME=finland

jobs:
  include:
   - stage: prebuild
     script: ./prebuild.sh

   - stage: build
     script: ./build-docker-image.sh

services:
 - docker

script:
 - true

install:
 - true
