sudo: required

branches:
  only:
    - master

language: C

jobs:
  include:
   - stage: test
     env: ROUTER_NAME=hsl
     script: ./prebuild.sh
   - stage: test
     env: ROUTER_NAME=waltti
     script: ./prebuild.sh
   - stage: test
     env: ROUTER_NAME=finland
     script: ./prebuild.sh

   - stage: build
     env: ROUTER_NAME=hsl
     script: ./build-docker-image.sh
   - stage: build
     env: ROUTER_NAME=waltti
     script: ./build-docker-image.sh
   - stage: build
     env: ROUTER_NAME=finland
     script: ./build-docker-image.sh

services:
 - docker

script:
 - true

install:
 - true
