sudo: required

branches:
  only:
    - master

language: python

env:
 - ROUTER_NAME=hsl
 - ROUTER_NAME=waltti
 - ROUTER_NAME=finland

services:
 - docker

before_install:
 - curl http://dev.hsl.fi/osm.finland/finland.osm.pbf -o finland.osm.pbf
 - curl http://dev.hsl.fi/osm.hsl/hsl.osm.pbf -o hsl.osm.pbf
 - docker pull hsldevcom/opentripplanner:prod

install:
 - true

script:
 - ./build-docker-image.sh

before_deploy:
 - echo "start deploying ..."
