sudo: required

branches:
  only:
    - master

language: C

jobs:
  include:
   - stage: prebuild
     env:
     - ROUTER_NAME=hsl
     - ROUTER_NAME=waltti
     - ROUTER_NAME=finland
     script: ./prebuild.sh

   - stage: build
     env:
     - ROUTER_NAME=hsl
     - ROUTER_NAME=waltti
     - ROUTER_NAME=finland
     script: ./build-docker-image.sh

services:
 - docker

script:
 - true

install:
 - true
